sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJY3jFXUKvcuX4Wi9JL
    access-key-secret: rcqk9I1NSdXtzqJ9GschXmIZkJ999l
    bucket-name: web-tlias-ww
  redis:
    host : localhost
    port : 6379
    database : 10
  wechat:
    appid: wx18bc3543dbc202a6
    secret: 8e3879edb9067a7d10f5debf2abcb15a
